# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

variables:
  LoggingOptions: '-Dorg.slf4j.simpleLogger.defaultLogLevel=error -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  displayName: 'Compile application'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'compile'
    mavenOptions: '$(LoggingOptions)'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
- powershell: |
    # Using an input-macro:
    Write-Host "This works: $(AZURE_APPCONFIG)"

    # Using the mapped env var:
    Write-Host "This works: $env:MY_MAPPED_ENV_VAR"    # Recommended
  env:
    MY_MAPPED_ENV_VAR: '$(AZURE_APPCONFIG)'

- task: Maven@3
  displayName: 'Run tests'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'test'
    mavenOptions: '$(LoggingOptions)'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'